apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: consul-sidekick
  namespace: loki
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - pods
  - replicasets
  verbs:
  - get
  - list
  - watch

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-sidekick
  namespace: loki

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: consul-sidekick
  namespace: loki
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: consul-sidekick
subjects:
- kind: ServiceAccount
  name: consul-sidekick
  namespace: loki
