apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chaoskube
  namespace: monitoring
spec:
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: chaoskube
    version: 3.1.4
  values:
    namespaces: "!monitoring"
    dryRun: false
    debug: false
    interval: 2m # m = min., s = sec.
    logFormat: json
    metrics:
      enabled: true
      port: 8080
    rbac:
      create: true
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
