apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses: # `$ docker network inspect bridge | jq .[0].IPAM.Config[0].Subnet`
      - 172.17.255.1-172.17.255.250

