apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-system
spec:
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: kube-state-metrics
    version: 2.8.5
