apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: metrics-server
    version: 2.11.1
  values:
    args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP
