apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco
  namespace: monitoring

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco
rules:
- apiGroups: ["extensions", ""]
  resources: ["nodes", "namespaces", "pods", "services", "events", "configmaps"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/healthz", "healthz/*"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: falco
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: falco


