apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  helmVersion: v3
  chart:
    repository: https://grafana.github.io/loki/charts
    name: promtail
    version: 0.23.0
  values:
    image:
      repository: grafana/promtail
      tag: 1.5.0
      pullPolicy: IfNotPresent
    loki:
      serviceName: monitoring-loki.monitoring.svc.cluster.local
      servicePort: 3100
      serviceScheme: http
    pipelineStages:
    - docker: {}
    - match:
        selector: '{app="eventrouter"}'
        stages:
        - json:
            expressions:
              verb: verb
              event: event
        - json:
            source: event
            expressions:
              from: source
              type: type
              reason: reason
              message: message
        - timestamp:
            format: RFC3339
            source: ts
        - labels:
            event_verb: verb
            event_type: type
            event_reason: reason
        - output:
            source: message
    - match:
        selector: '{job="monitoring/monitoring-chaoskube"}'
        stages:
        - json:
            expressions:
              target_name: name
              target_namespace: namespace
              msg: msg
              timestamp: time
        - timestamp:
            format: RFC3339
            source: timestamp
        - labels:
            target_name: ""
            target_namespace: ""
        - output:
            source: msg

