apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  helmVersion: v3
  chart:
    repository: https://grafana.github.io/loki/charts
    name: promtail
    version: 0.23.0
  values:
    image:
      repository: grafana/promtail
      tag: 1.5.0
      pullPolicy: IfNotPresent
    loki:
      serviceName: monitoring-loki.monitoring.svc.cluster.local
      servicePort: 3100
      serviceScheme: http
    pipelineStages:
    - docker: {}
