# https://raw.githubusercontent.com/fluxcd/helm-operator/1.0.0/deploy/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: helm-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: helm-operator
      annotations:
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: helm-operator
      volumes:
      containers:
      - name: helm-operator
        image: docker.io/fluxcd/helm-operator:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3030
        livenessProbe:
          httpGet:
            port: 3030
            path: /healthz
          initialDelaySeconds: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: 3030
            path: /healthz
          initialDelaySeconds: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
        volumeMounts:
        args:
        # Comment out to enable a single Helm version that can be targeted
        # by a `HelmRelease`; defaults to `--enabled-helm-versions=v2,v3`.
        #
        - --enabled-helm-versions=v3
