{
 "title": "Server",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(cpu) (rate(node_cpu_seconds_total{mode!=\"idle\"}[2m]))",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Disk Read IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(device, kubernetes_node) (rate(node_disk_read_bytes_total[2m]))",
     "legendFormat": "{{kubernetes_node}}/{{device}}"
    }
   ]
  },
  {
   "title": "CPU Shares",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(kubernetes_io_hostname) (container_spec_cpu_shares{container!=\"\"}) / 1024 * 1000",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "load average 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "load average 5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "load average 15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "{{kubernetes_node}}" }
   ]
  }
 ]
}