{
 "title": "container",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "cpu shares per pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, namespace) (container_spec_cpu_shares{pod!=\"\", container=\"\"}) / 1024 * 1000",
     "legendFormat": "{{pod}}.{{namespace}}"
    }
   ]
  },
  {
   "title": "memory limits per pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, namespace) (container_spec_memory_limit_bytes{pod!=\"\", container=\"\"})",
     "legendFormat": "{{pod}}.{{namespace}}"
    }
   ]
  },
  {
   "title": "cpu utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, namespace) (rate(container_cpu_usage_seconds_total[2m])) / sum by(pod, namespace) (container_spec_cpu_quota / container_spec_cpu_period)",
     "legendFormat": "{{pod}}.{{namespace}}"
    }
   ]
  },
  {
   "title": "memory utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod, namespace) (container_memory_working_set_bytes{pod!=\"\"})",
     "legendFormat": "{{pod}}.{{namespace}}"
    }
   ]
  },
  {
   "title": "disk utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (container_fs_writes_bytes_total{container!=\"\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Loki request duration seconds p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(status_code, le) (rate(loki_request_duration_seconds_bucket[2m])))",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}