# https://github.com/helm/charts/tree/master/stable/grafana
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: grafana
    version: 5.0.26
  values:
    adminPassword: admin
    service:
      type: NodePort
      nodePort: 30000
    image:
      repository: grafana/grafana
      tag: 7.0.0
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: prometheus
          type: prometheus
          url: http://vm-victoria-metrics-cluster-vmselect.monitoring.svc.cluster.local:8481/select/0/prometheus
          # access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://monitoring-loki.monitoring.svc.cluster.local:3100
          # access: proxy
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'server'
          orgId: 1
          folder: 'os'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/server
        - name: 'k8s'
          orgId: 1
          folder: 'os'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/k8s
        - name: 'container'
          orgId: 1
          folder: 'os'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/container
        - name: 'monitoring'
          orgId: 1
          folder: 'app'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/monitoring
    extraConfigmapMounts:
    - name: dashboard-server-configmap
      configMap: grafana-dashboard-server
      mountPath: /var/lib/grafana/dashboards/server
      readOnly: true
    - name: dashboard-k8s-configmap
      configMap: grafana-dashboard-k8s
      mountPath: /var/lib/grafana/dashboards/k8s
      readOnly: true
    - name: dashboard-container-configmap
      configMap: grafana-dashboard-container
      mountPath: /var/lib/grafana/dashboards/container
      readOnly: true
    - name: dashboard-monitoring-configmap
      configMap: grafana-dashboard-monitoring
      mountPath: /var/lib/grafana/dashboards/monitoring
      readOnly: true
