apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: grafana
    version: 5.0.26
  values:
    adminPassword: admin
    service:
      type: NodePort
    image:
      repository: grafana/grafana
      tag: 7.0.0
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-prometheus-server.monitoring.svc.cluster.local:80
          # access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://monitoring-loki.monitoring.svc.cluster.local:3100
          # access: proxy
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'server'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/server
        - name: 'k8s'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/k8s
    extraConfigmapMounts:
    - name: dashboard-server-configmap
      configMap: grafana-dashboard-server
      mountPath: /var/lib/grafana/dashboards/server
      readOnly: true
    - name: dashboard-k8s-configmap
      configMap: grafana-dashboard-k8s
      mountPath: /var/lib/grafana/dashboards/k8s
      readOnly: true
