{
 "title": "k8s",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Pod scheduling status phase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(phase) (kube_pod_status_phase{phase!=\"Running\"})",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Container waiting reason",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(reason, container) (kube_pod_container_status_waiting_reason)",
     "legendFormat": "[{{reason}}] {{container}}"
    }
   ]
  },
  {
   "title": "Deployment spec replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kube_deployment_spec_replicas", "legendFormat": "{{deployment}}.{{namespace}}" }
   ]
  },
  {
   "title": "Deployment Unavailable replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas - kube_deployment_status_replicas_available",
     "legendFormat": "{{deployment}}.{{namespace}}"
    }
   ]
  },
  {
   "title": "Daemon/StatefulSet desired",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_daemonset_status_desired_number_scheduled",
     "legendFormat": "{{daemonset}}.{{namespace}}"
    },
    { "expr": "kube_statefulset_replicas", "legendFormat": "{{statefulset}}.{{namespace}}" }
   ]
  },
  {
   "title": "Daemon/StatefulSet unavailables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_daemonset_status_desired_number_scheduled - kube_daemonset_status_number_available",
     "legendFormat": "{{daemonset}}.{{namespace}}"
    },
    {
     "expr": "kube_statefulset_status_replicas_current",
     "legendFormat": "{{statefulset}}.{{namespace}}"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_endpoint_address_available",
     "legendFormat": "{{endpoint}}.{{namespace}}"
    }
   ]
  }
 ]
}