{
 "title": "monitoring tools",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "prometheus request duration (99p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, handler) (rate(prometheus_http_request_duration_seconds_bucket[2m])))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "loki request duration seconds (99p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, status_code, release) (rate(loki_request_duration_seconds_bucket[2m])))",
     "legendFormat": "{{release}}: {{status_code}}"
    }
   ]
  },
  {
   "title": "loki cache corrupt chunks (per second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(cortex_cache_corrupt_chunks_total[2m])",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "loki flush queue length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cortex_ingester_flush_queue_length",
     "legendFormat": "{{release}}"
    }
   ]
  }
 ]
}