{
 "title": "Server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "load average 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "load average 5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "load average 15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "{{kubernetes_node}}" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(cpu, kubernetes_node) (rate(node_cpu_seconds_total{mode!=\"idle\"}[2m]))",
     "legendFormat": "{{cpu}}.{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "memory utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "memory swap rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes))",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "disk utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg(node_filesystem_avail_bytes / node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "inode utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg(node_filesystem_files_free / node_filesystem_files)"
    }
   ]
  },
  {
   "title": "disk read latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total[2m]) / rate(node_disk_reads_completed_total[2m])",
     "legendFormat": "{{device}}/{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "disk write latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total[2m]) / rate(node_disk_writes_completed_total[2m])",
     "legendFormat": "{{device}}/{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "disk saturation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total[2m])",
     "legendFormat": "{{device}}/{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "network receice bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[2m])",
     "legendFormat": "{{device}}/{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "network send bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total[2m])",
     "legendFormat": "{{device}}/{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "network receive saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total[2m])",
     "legendFormat": "{{device}}/{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "network send saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_drop_total[2m])",
     "legendFormat": "{{device}}/{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "network receive errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total[2m])",
     "legendFormat": "{{device}}/{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "network send errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_errs_total[2m])",
     "legendFormat": "{{device}}/{{kubernetes_node}}"
    }
   ]
  }
 ]
}